project:
  type: website
  output-dir: docs

website:
  title: "Naseem H. Dillman-Hasso"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Publications
      - href: grants.qmd
        text: Grants and Awards
      - href: teaching.qmd
        text: Teaching
      - href: files/cv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full