---
title: "Publications"
---
Citation counts can be found on [Google Scholar](https://scholar.google.com/citations?user=xxDtDtwAAAAJ&hl=en).

## In progress
- **Dillman-Hasso, N. H.** A Meta-Analysis on the Persistent Effects of Incentives on Pro-Environmental Behavior Change Interventions. (Revise and Resubmit submitted at Journal of Environmental Psychology)
- **Dillman-Hasso, N. H.**, Le, P. Q., Fujita, K., Wilson, R. Using narratives to promote goal reflection and pro-environmental behavioral intentions. In prep.
- Sintov, N. D., Hurst, K., **Dillman-Hasso, N. H.** How families shape residential solar adoption. In prep for Nature Energy.
- **Dillman-Hasso, N. D.**, Fujita, K. Understanding psychological distance and environmental behaviors from a regulatory scope perspective. In prep.

## Motivations for Behavior Change
- Shaffer‐Morrison, C. D., **Dillman‐Hasso, N. H.**, & Wilson, R. S. (2025). Sowing seeds for the future: Future time perspective and climate adaptation among farmers. British Journal of Social Psychology, 64(2), e12850. doi.org/10.1111/bjso.12850. [Link](https://doi.org/10.1111/bjso.12850).

## Large Sustainable Behaviors
- **Dillman-Hasso, N. H.**, Sintov, N. D. (2025). Can we achieve equity in residential solar adoption? Public perceptions of rooftop and community solar in the United States. Energy Research & Social Science, 122, 104022. doi.org/10.1016/j.erss.2025.104022. [Link](https://doi.org/10.1016/j.erss.2025.104022).

## Listening Effort
- Wennberg, J., **Dillman-Hasso, N. H.**, Strand, J. F., Brown, V. A. (Registered Report Round 2 Revision Submitted). Impaired Performance in Noise: Disentangling Listening Effort from the Irrelevant Speech Effect. Collabra: Psychology. Registered Report.
- Brown, V. A., **Dillman-Hasso, N. H.**, Li, Z., Ray, L., Mamantov, E., Van Engen, K. J., & Strand, J. F. (2022). Revisiting the target-masker linguistic similarity hypothesis. Attention, Perception, & Psychophysics, 1-16. [Link](https://doi.org/10.3758/s13414-022-02486-3).
- Strand, J.F., Ray, L., **Dillman-Hasso, N. H.**, Villanueva, J., Brown, V. A. (2020). Understanding Speech amid the Jingle and Jangle: Recommendations for Improving Measurement Practices in Listening Effort Research. Auditory Perception & Cognition, doi.org/10.1080/25742442.2021.1903293. [Link](https://doi.org/10.1080/25742442.2021.1903293).
- Guang, C., Lefkowitz, E., **Dillman-Hasso, N. H.**, Brown, V., & Strand, J. F. (2020). Recall of Speech is Impaired by Subsequent Masking Noise: A Replication of Rabbitt (1968) Experiment 2. Auditory Perception & Cognition, 1-10. doi.org/10.1080/25742442.2021.1896908. [Link](https://doi.org/10.1080/25742442.2021.1896908).
- Brown, V. A., Hedayati, M., Zanger, A., Mayn, S., Ray, L., **Dillman-Hasso, N. H.**, & Strand, J. F. (2018). What accounts for individual differences in susceptibility to the McGurk effect?. PLoS ONE, 1. doi.org/10.1371/journal.pone.0207160. [Link](https://doi.org/10.1371/journal.pone.0207160).

## Other
- **Dillman-Hasso, N. H.** (2021). The nature buffer: the missing link in climate change and mental health research. Journal of Environmental Studies and Sciences, 1-6. doi.org/10.1007/s13412-021-00669-2. [Link](https://doi.org/10.1007/s13412-021-00669-2).
- **Dillman-Hasso, N. H.** (2020). When the nature of ‘nature’ is inconsistent: Evaluating the natural environment in Attention Restoration Theory. doi.org/10.31234/osf.io/w36rg. [Link](https://doi.org/10.31234/osf.io/w36rg).