---
title: "Grants and Awards"
---

## Research Grants

### External: $31,515
- 2025: NSF DRMS Doctoral Dissertation Research Improvement Grant (Co-PI with Dr. Robyn Wilson). $29.952. *Doctoral Dissertation Research: Understanding and Promoting Pro-Environmental Behavior Change Through Regulatory Scope*
- 2025: Fall 2024 Society for the Improvement of Psychological Science Grant-in-Aid. $938.
- 2024: Society for Personality and Social Psychology Grant. $625

### Internal: $6,820
- 2024: OSU Alumni Grants for Graduate Research and Scholarship. $3,500
- 2024: OSU School of Environment and Natural Resources GradRoots Minigrant. $500
- 2023: OSU Decision Sciences Collaborative Reserach Grant. $2,820.

## Awards, Fellowships, & Certifications
- 2025: Certification in Effective Teaching Practices through the Association of College and University Educators
- 2025: Graduate Associate Teaching Award at Ohio State University ($2,000)
- 2024: SPSP Community Catalyst Grant for SALAAM ($2,000)
- 2024: OSU School of Environment and Natural Resources Chili Cookoff Winner ($15)
- 2024: Best Flash Talk at the Sustainability Preconference at SPSP
- 2022: Society for Risk Analysis Student Travel Award ($500)
- 2021: University Fellowship from The Ohio State University ($30,420)
- 2021: National Science Foundation Graduate Research Fellowship Honorable Mention
- 2021: APS Observer Up-And-Coming Voice
