---
title: "Teaching and Mentoring"
---
# Formal instruction
## At The Ohio State University
### As Instructor of Record
- ENR 5400 (Interventions to Promote Pro-Environmental Behavior)
  - Spring 2025. N = 29. Rated 5/5 in student evaluations.
  - Spring 2024. N = 18. Rated 4.9/5 in student evaluations.
- ENR 3400 (Psychology of Environmental Problems)
  - Fall 2024. N = 97. Rated 4.7/5 in student evaluations.

### As TA
- ENR 3400 (Psychology of Environmental Problems)
  - Fall 2025 (In progress): N ≈ 110
  - Fall 2023: N = 109. No student evaluation data collected.
  - Fall 2022: N = 90. Rated 4.45/5 in student evaluations.
- ENR 3200 (Environment and Natural Resource Policy)
  - Spring 2023. N = 125. No student evaluation data collected.


## At Carleton College
- Winter 2020 TA for PSYC200 + Lab: Measurement and Data Analysis. N = 45
- Winter, Spring, and Fall 2019. Prefect (similar to TA) for PSYC110: Intro to Psychology. Ns ranged from 35-70.

# Informal instruction
- Led multiple R coding/analysis tutorials